[data]
batch_size = 192
segment_size = 32
dataset_path = "da-en/europarl-v7.da-en.da"
# dataset_path = "da-en/test.txt"

[model]
dropout = 0.3
bert_uri = "Maltehb/danish-bert-botxo"
output_dir = "outputs"
status_interval = 10000

[training.head]
criterion = "BCELoss"
optimizer = "Adam"
lr        = [1e-5]
epochs    = [5]

[training.full]
criterion = "BCELoss"
optimizer = "Adam"
lr        = [1e-5]
epochs    = [3]
